name: CI/CD POC (Servidor Simulado)

on:
  push:
    branches: [ "main" ]

jobs:
  simulacao-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Pega o código atualizado do GitHub
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Constrói a imagem Docker da aplicação (Fase CI)
      - name: Construir a imagem Docker
        run: docker build -t site-turismo .

      # 3. Simula o servidor iniciando o container com o código novo (Fase CD)
      - name: Iniciar o Servidor Simulado (Docker)
        run: docker run -d --name servidor-teste -p 8000:8000 site-turismo

      # 4. Prova de Conceito: Testa se o servidor simulado está rodando a aplicação
      - name: Testar se o sistema atualizou e está no ar
        run: |
          sleep 5
          curl http://localhost:8000